messages:
  death:
    - "&8&m----------- &c&lYOU HAVE DIED&8&m -----------"
    - "&r"
    - "&fYou can use &e/lastdeath &for &e/death"
    - "&fto return to the place of your death."
    - "&r"
    - "&8&m----------- &c&lYOU HAVE DIED&8&m -----------"
  back-success: "&aYou have returned to the place of your death."
  back-no-location: "&cYou do not have a saved death location."
  only-player: "&cThis command can only be used by players."
  reload-success: "&aConfiguration reloaded successfully."
  no-permission: "&cYou do not have permission to execute this command."
  unknown-command: "&cUnregistered command, use: &e/adeath reload."